import Foundation

let anonymousName = "The Stig"

// Typo corrections dictionary for vehicle series names
let typoCorrections: [String: String] = [
  "$$_posthog_breakdown_null_$$": anonymousName,
  "/": anonymousName,
  "/Civic": "Honda/Civic",
  "/Creta": "Hyundai/Creta",
  "/Giulia": "Alfa Romeo/Giulia",
  "/Teramount": "Volkswagen/Teramont",
  "2019/Mazda2": "Mazda/Mazda2",
  "Accent/": "Hyundai/Accent",
  "AGM/GMX 450": anonymousName,
  "Alfa Romeo/Guilia": "Alfa Romeo/Giulia",
  "AUDIdi/Q3": "Audi/Q3",
  "Audu/S6 Avant e-tron": "Audi/A6 e-tron",
  "Azera /MDE": "Hyundai/Azera",
  "B/B": anonymousName,
  "Bd/Hd": anonymousName,
  "Bdbb/Bzbxb": anonymousName,
  "BME/G20 330i": "BMW/3 Series",
  "BMW/IX1": "BMW/iX1",
  "BMW/Serie 1 ": "BMW/1 Series",
  "Bmw/740li": "BMW/7 Series",
  "Camry/24": "Toyota/Camry",
  "Camry/Camry": "Toyota/Camry",
  "Chanagan/Uni K": "Changan/UNI-K",
  "Changan /Uni-v": "Changan/UNI-V",
  "Changan /UNI-V": "Changan/UNI-V",
  "changan/uni-v": "Changan/UNI-V",
  "Changan/Uni-v": "Changan/UNI-V",
  "Changhan/Eado plse": "Changan/Eado Plus",
  "Chary/Tigoo8 pro": "Chery/Tiggo 8 Pro",
  "Cheery/Areezo8": "Chery/Arrizo 8",
  "Cherry /Teggo pro 7": "Chery/Tiggo 7 Pro",
  "Cherry/Arizo 6. Pro": "Chery/Arrizo 6 Pro",
  "CHERRY/Arrizo8": "Chery/Arrizo 8",
  "Cherry/Tiggo 8 pro": "Chery/Tiggo 8 Pro",
  "Chery /Tiggo 8 Pro": "Chery/Tiggo 8 Pro",
  "Chevorlat/Tahoe": "Chevrolet/Tahoe",
  "Chevorlet/Grove": "Chevrolet/Groove",
  "Chevorlet/Malibu": "Chevrolet/Malibu",
  "Chevrolet/Malibeu": "Chevrolet/Malibu",
  "Chevrolet/Taho": "Chevrolet/Tahoe",
  "Chevrolet3022/Blazer": "Chevrolet/Blazer",
  "Chevy/Sonic": "Chevrolet/Sonic",
  "Cxfhhhvv/Hhhc.": anonymousName,
  "Defender/2021": "Land Rover/Defender",
  "Defender/Defender": "Land Rover/Defender",
  "Eagle/Renulet megan": "Renault/Megane",
  "Elantra/Smart": "Hyundai/Elantra",
  "Ford Taurus/2023": "Ford/Taurus",
  "Ford/everest": "Ford/Everest",
  "Ford/EVEREST": "Ford/Everest",
  "Ford/expdition": "Ford/Expedition",
  "Ford/Mavrick": "Ford/Maverick",
  "Ford/Ranger rapter": "Ford/Ranger",
  "Ford/ta": "Ford/Taurus",
  "Ford/Tauros": "Ford/Taurus",
  "Ford/Taurs": "Ford/Taurus",
  "Ford/Teratoury": "Ford/Territory",
  "Ford/Teritory": "Ford/Territory",
  "Ford/Terytory": "Ford/Territory",
  "Ford/Toto": "Ford/Taurus",
  "Ford/Touars": "Ford/Taurus",
  "Ford/Touros": "Ford/Taurus",
  "Ford/Tours": "Ford/Taurus",
  "Ford/Tourus": "Ford/Taurus",
  "Ford/Turas": "Ford/Taurus",
  "Ford/Tures": "Ford/Taurus",
  "Ford/Turua": "Ford/Taurus",
  "Fordtaurus/Taurus": "Ford/Taurus",
  "Gacambao/athlete": anonymousName,
  "GMC/Sieera": "GMC/Sierra",
  "googl.com/": anonymousName,
  "Greatwallmotor/HAVAL JOLION": "GWM/Haval Jolion",
  "hawndi/tucan": "Hyundai/Tucson",
  "Heundai/Azera": "Hyundai/Azera",
  "Hindai/Elntra": "Hyundai/Elantra",
  "Hionday/Elantra": "Hyundai/Elantra",
  "Honda/Accourd": "Honda/Accord",
  "Honda/Accrod": "Honda/Accord",
  "Honda/Acord": "Honda/Accord",
  "Honda/Acurd": "Honda/Accord",
  "Honda/Cvic": "Honda/Civic",
  "Honda/Oddyssey": "Honda/Odyssey",
  "Honda/Pliot": "Honda/Pilot",
  "Hondai/Accent": "Hyundai/Accent",
  "Hondai/Taycan": "Porsche/Taycan",
  "Hondi azera/": "Hyundai/Azera",
  "Hounday/T": "Hyundai/Tucson",
  "Hunda Accord /4dr": "Honda/Accord",
  "Hundai/2025": anonymousName,
  "Hundai/Creta": "Hyundai/Creta",
  "Hundai/Krita": "Hyundai/Creta",
  "Hunday/Tucson": "Hyundai/Tucson",
  "Huyndai/Accent": "Hyundai/Accent",
  "Huyndai/Yuscon": "Hyundai/Tucson",
  "Hyandiy/Azera": "Hyundai/Azera",
  "Hynday/Azera": "Hyundai/Azera",
  "Hyndai/Sonata": "Hyundai/Sonata",
  "Hyonday/Elentra": "Hyundai/Elantra",
  "Hyunai/Elantra": "Hyundai/Elantra",
  "Hyundai/Azira": "Hyundai/Azera",
  "Hyundai/Elantr": "Hyundai/Elantra",
  "Hyundai/Elentra": "Hyundai/Elantra",
  "Hyundai/ELNTRA": "Hyundai/Elantra",
  "Hyundai/GRANDUAR": "Hyundai/Grandeur",
  "Hyundai/Ionoiq 5": "Hyundai/IONIQ 5",
  "Hyundai/Somata": "Hyundai/Sonata",
  "Hyundai6/Accent": "Hyundai/Accent",
  "Hyundi/Elantra": "Hyundai/Elantra",
  "Hyundi/Elentra": "Hyundai/Elantra",
  "Hyundia/Ioniq 5": "Hyundai/IONIQ 5",
  "hyundia /Sonata": "Hyundai/Sonata",
  "Hyundia/Sonata": "Hyundai/Sonata",
  "In korea/G80": "Genesis/G80",
  "Jeep/Grand Cherockee": "Jeep/Grand Cherokee",
  "Jetour /T2": "Jetour/T2",
  "JETOUR /T2": "Jetour/T2",
  "jetour/t2": "Jetour/T2",
  "K5/": "Kia/K5",
  "Kai/K5": "Kia/K5",
  "Kai/Optima": "Kia/Optima",
  "Kia/KIA5": "Kia/K5",
  "Kis/Ev9": "Kia/EV9",
  "Land Rover/Autobiograpgy": "Land Rover/Range Rover",
  "Land Rover/Devender": "Land Rover/Defender",
  "Lexus/Lexus": anonymousName,
  "Lexus/Rx450+": "Lexus/RX",
  "Linclon/Neutilus": "Lincoln/Nautilus",
  "Luczs/Is259": "Lexus/IS",
  "Ma/Outback": "Subaru/Outback",
  "Maruti /Baleno": "Maruti Suzuki/Baleno",
  "Mazada/Mazada 6": "Mazda/Mazda6",
  "Mazda/MX-5 Miata RF": "Mazda/MX-5",
  "Mazda/MX-5 Miata": "Mazda/MX-5",
  "Mazda 6/": "Mazda/Mazda6",
  "Meganr/": "Renault/Megane",
  "Mercedec/G class": "Mercedes-Benz/G-Class",
  "Mercedes /": "Mercedes-Benz/",
  "Mercedes /Clk": "Mercedes-Benz/CLK-Class",
  "Mercedes /G 63": "Mercedes-Benz/G-Class",
  "Mercedes-Benzv/C 200": "Mercedes-Benz/C-Class",
  "Mercedes/C200": "Mercedes-Benz/C-Class",
  "Mercedes/C300": "Mercedes-Benz/C-Class",
  "Mercedes/CLA250": "Mercedes-Benz/CLA-Class",
  "Mercedes/Classe c": "Mercedes-Benz/C-Class",
  "Mercedes/E 300": "Mercedes-Benz/E-Class",
  "Mercedes/E200": "Mercedes-Benz/E-Class",
  "Mercedes/Ecitan": "Mercedes-Benz/Citan",
  "Mercedes/Gla 220": "Mercedes-Benz/GLA-Class",
  "Mercedes/GLE 43 Coupe AMG": "Mercedes-Benz/GLE-Class",
  "Mercedes/Gle 53 coupe": "Mercedes-Benz/GLE-Class",
  "Mercedes/Sprinter": "Mercedes-Benz/Sprinter",
  "Mercedez-Benz/Glc": "Mercedes-Benz/GLC-Class",
  "MG-ZS/": "MG/ZS",
  "Nisaan /Patrol": "Nissan/Patrol",
  "Nisaan/patrol": "Nissan/Patrol",
  "Nisaan/Platinum": "Nissan/Patrol",
  "Nisan NISMO /2024": "Nissan/370Z",
  "Nissan Altama/S": "Nissan/Altima",
  "Nissan/ALITMIMA": "Nissan/Altima",
  "Nissan/Altama": "Nissan/Altima",
  "Nissan/Nissan Patrol": "Nissan/Patrol",
  "Nissan/Qashqaj": "Nissan/Qashqai",
  "Nissan/The tima": "Nissan/Altima",
  "Nissanpatrol/Patrol": "Nissan/Patrol",
  "Nussan/Patrol": "Nissan/Patrol",
  "Opel /Opel mokka": "Opel/Mokka",
  "OPEL/Astra Sports Tourwr": "OPEL/Astra",
  "OPEL/Granland": "OPEL/Grandland",
  "OPEL/Insigna": "OPEL/Insignia",
  "P/E": anonymousName,
  "Pe/3008": "Peugeot/3008",
  "peugeot iran khodro/207": "Peugeot/207",
  "Porsxhe/Taycan": "Porsche/Taycan",
  "rabdan/one": anonymousName,
  "Range Rover /Velar": "Land Rover/Range Rover Velar",
  "Renault/Kadjarr": "Renault/Kadjar",
  "Renoult/Clio 4": "Renault/Clio",
  "Rox 01 /Rox 01": anonymousName,
  "Sangyoung/Rexston": "SsangYong/Rexton",
  "Skods/Octavia": "Skoda/Octavia",
  "Sonata/2025": "Hyundai/Sonata",
  "SssngYong/": "SsangYong/",
  "suzki/": "Suzuki/",
  "TAURUS/2025": "Ford/Taurus",
  "Taurus/Titanim": "Ford/Taurus",
  "Touots /corolla": "Toyota/Corolla",
  "Toyoa/Land crusier": "Toyota/Land Cruiser",
  "Toyota land cruiser/LC300": "Toyota/Land Cruiser",
  "Toyota/Camrey": "Toyota/Camry",
  "Toyota/Cammry": "Toyota/Camry",
  "Toyota/corola": "Toyota/Corolla",
  "Toyota/Corola": "Toyota/Corolla",
  "Toyota/HILLIX": "Toyota/Hilux",
  "Toyota/Hillux": "Toyota/Hilux",
  "Toyota/Land Crusier LC300": "Toyota/Land Cruiser",
  "Toyota/Land crusier": "Toyota/Land Cruiser",
  "Toyota/Land cruser": "Toyota/Land Cruiser",
  "Toyota/Land cruiser VXR": "Toyota/Land Cruiser",
  "Toyotaw/Crown": "Toyota/Crown",
  "Toyote/Land cruiser": "Toyota/Land Cruiser",
  "Toyta/Crolla": "Toyota/Corolla",
  "Unknown": anonymousName,
  "Unknown/Unknown": anonymousName,
  "Vauxhall /Insignia": "Vauxhall/Insignia",
  "Vauxhaull/Astra": "Vauxhall/Astra",
  "Vlvo/V70": "Volvo/V70",
  "volkeswagen/tiguan": "Volkswagen/Tiguan",
  "Volkswag/Fox": "Volkswagen/Fox",
  "Volkswageb/Poli": "Volkswagen/Polo",
  "Volkswagee/Virtus": "Volkswagen/Virtus",
  "Volkswagen/Goal": "Volkswagen/Golf",
  "Volkswagen/Golff": "Volkswagen/Golf",
  "Volkswagen/Pasat": "Volkswagen/Passat",
  "Volkswagen/T roc cabriolet": "Volkswagen/T-Roc",
  "Volkswagen/Tcross 2021": "Volkswagen/T-Cross",
  "Volkswagen/Twareg": "Volkswagen/Touareg",
  "Volkwagen/Virtus": "Volkswagen/Virtus",
  "Volvov/XC60": "Volvo/XC60",
  "VW/Id.6": "Volkswagen/ID.6",
  "VW/Id3": "Volkswagen/ID.3",
  "Vw/Id4": "Volkswagen/ID.4",
  "VW/ID4": "Volkswagen/ID.4",
  "VW/ID6": "Volkswagen/ID.6",
  "Vw/Idbuzz": "Volkswagen/ID.Buzz",
  "WVGZZZ5NZMW541659/": anonymousName,
  "Xbb/Jxbxj": anonymousName,
  "Yoyota/Corolla": "Toyota/Corolla",

  // BMW model to series consolidation
  "BMW/325xi": "BMW/3 Series",
  "BMW/330e": "BMW/3 Series",
  "BMW/330i": "BMW/3 Series",
  "BMW/335i": "BMW/3 Series",
  "BMW/328i": "BMW/3 Series",
  "BMW/320i": "BMW/3 Series",
  "BMW/320d": "BMW/3 Series",
  "BMW/320D": "BMW/3 Series",
  "BMW/323i": "BMW/3 Series",
  "BMW/340i": "BMW/3 Series",
  "BMW/335d": "BMW/3 Series",
  "BMW/E46": "BMW/3 Series",
  "BMW/E90": "BMW/3 Series",
  "BMW/E91": "BMW/3 Series",
  "BMW/F31": "BMW/3 Series",
  "BMW/G20": "BMW/3 Series",
  "BMW/Serie 3": "BMW/3 Series",
  "BMW/Serie1": "BMW/1 Series",
  "BMW/Series 3": "BMW/3 Series",
  "BMW/Series 1": "BMW/1 Series",
  "BMW/3": "BMW/3 Series",
  "BMW/3er": "BMW/3 Series",
  "BMW/1er": "BMW/1 Series",
  "BMW/3 series Touring": "BMW/3 Series",
  "BMW/Serie 3 F34 GT": "BMW/3 Series",
  "BMW/M340i": "BMW/3 Series",
  "BMW/M340d": "BMW/3 Series",
  "BMW/M340i Xdrive": "BMW/3 Series",
  "BMW/M340XI": "BMW/3 Series",
  "BMW/318i": "BMW/3 Series",
  "BMW/318i LCI": "BMW/3 Series",
  "BMW/320D M Sport": "BMW/3 Series",
  "BMW/320D EFFICIENT DYNAMICS": "BMW/3 Series",
  "BMW/328": "BMW/3 Series",
  "BMW/335d Xdrive": "BMW/3 Series",
  "BMW/G20 330i": "BMW/3 Series",
  "BMW/I330": "BMW/3 Series",
  "BMW/325i/325is": "BMW/3 Series",

  // BMW 1 Series
  "BMW/128i": "BMW/1 Series",
  "BMW/125i": "BMW/1 Series",
  "BMW/118d": "BMW/1 Series",
  "BMW/118i": "BMW/1 Series",
  "BMW/123": "BMW/1 Series",
  "BMW/128 Ti": "BMW/1 Series",
  "BMW/M140i": "BMW/1 Series",
  "BMW/M135i xDrive": "BMW/1 Series",
  "BMW/M135 f 40": "BMW/1 Series",
  "BMW/M135": "BMW/1 Series",
  "BMW/E82": "BMW/1 Series",
  "BMW/E82 1 SERIES": "BMW/1 Series",
  "BMW/F20": "BMW/1 Series",
  "BMW/1 Series M": "BMW/1 Series",
  "BMW/Serie 1": "BMW/1 Series",

  // BMW 2 Series
  "BMW/M240i": "BMW/2 Series",
  "BMW/M240i xdrive": "BMW/2 Series",
  "BMW/M240i x-drive": "BMW/2 Series",
  "BMW/218i": "BMW/2 Series",
  "BMW/220i": "BMW/2 Series",
  "BMW/220i Coupe": "BMW/2 Series",
  "BMW/220i Cabriolet Steptronic": "BMW/2 Series",
  "BMW/228i": "BMW/2 Series",
  "BMW/M235i": "BMW/2 Series",
  "BMW/Serie 2": "BMW/2 Series",
  "BMW/ActiveTourer 2": "BMW/2 Series",
  "BMW/2 Series Gran Coupe": "BMW/2 Series",

  // BMW 4 Series
  "BMW/430i": "BMW/4 Series",
  "BMW/440i": "BMW/4 Series",
  "BMW/420d": "BMW/4 Series",
  "BMW/420i xdrive": "BMW/4 Series",
  "BMW/428i": "BMW/4 Series",
  "BMW/428i xDrive": "BMW/4 Series",
  "BMW/428 f32": "BMW/4 Series",
  "BMW/430d": "BMW/4 Series",
  "BMW/M440i": "BMW/4 Series",
  "BMW/M440i xDrive": "BMW/4 Series",
  "BMW/4.20i": "BMW/4 Series",

  // BMW 5 Series
  "BMW/530i": "BMW/5 Series",
  "BMW/530i xDrive": "BMW/5 Series",
  "BMW/530i E39": "BMW/5 Series",
  "BMW/530e": "BMW/5 Series",
  "BMW/530": "BMW/5 Series",
  "BMW/530D": "BMW/5 Series",
  "BMW/530D xdrive": "BMW/5 Series",
  "BMW/520i": "BMW/5 Series",
  "BMW/520i Touring": "BMW/5 Series",
  "BMW/520d": "BMW/5 Series",
  "BMW/520D": "BMW/5 Series",
  "BMW/520d Touring": "BMW/5 Series",
  "BMW/520": "BMW/5 Series",
  "BMW/540i": "BMW/5 Series",
  "BMW/545e": "BMW/5 Series",
  "BMW/550i": "BMW/5 Series",
  "BMW/550e": "BMW/5 Series",
  "BMW/528i": "BMW/5 Series",
  "BMW/535d": "BMW/5 Series",
  "BMW/5": "BMW/5 Series",
  "BMW/5 serie": "BMW/5 Series",
  "BMW/5 Series 520d": "BMW/5 Series",
  "BMW/E39": "BMW/5 Series",
  "BMW/G30 530e": "BMW/5 Series",
  "BMW/G31": "BMW/5 Series",
  "BMW/M550i": "BMW/5 Series",
  "BMW/Bmw 545e": "BMW/5 Series",

  // BMW 6 Series
  "BMW/640d": "BMW/6 Series",
  "BMW/M6 Gran Coupe": "BMW/6 Series",

  // BMW 7 Series
  "BMW/740i": "BMW/7 Series",
  "BMW/750i": "BMW/7 Series",
  "BMW/750 li": "BMW/7 Series",
  "BMW/750LiX": "BMW/7 Series",
  "BMW/730": "BMW/7 Series",
  "BMW/730D": "BMW/7 Series",
  "BMW/740d xdrive": "BMW/7 Series",
  "BMW/Li730": "BMW/7 Series",
  "/Bmw 740li": "BMW/7 Series",

  // BMW 8 Series
  "BMW/M850i": "BMW/8 Series",
  "BMW/8 Series Gran Coupe": "BMW/8 Series",
  "BMW/BMW 840i Gran Coupe": "BMW/8 Series",

  // Mercedes-Benz C-Class
  "Mercedes-Benz/C 200": "Mercedes-Benz/C-Class",
  "Mercedes-Benz/C 220": "Mercedes-Benz/C-Class",
  "Mercedes-Benz/C 300": "Mercedes-Benz/C-Class",
  "Mercedes-Benz/C 250": "Mercedes-Benz/C-Class",
  "Mercedes-Benz/C 350": "Mercedes-Benz/C-Class",
  "Mercedes-Benz/C 280": "Mercedes-Benz/C-Class",
  "Mercedes-Benz/C 63 AMG": "Mercedes-Benz/C-Class",
  "Mercedes-Benz/C350e": "Mercedes-Benz/C-Class",
  "Mercedes-Benz/C400": "Mercedes-Benz/C-Class",
  "Mercedes-Benz/C43 AMG": "Mercedes-Benz/C-Class",
  "Mercedes-Benz/C230 Kompressor": "Mercedes-Benz/C-Class",
  "Mercedes-Benz/AMG C 43": "Mercedes-Benz/C-Class",
  "Mercedes-Benz/C": "Mercedes-Benz/C-Class",
  "Mercedes-Benz/W205 Wagon": "Mercedes-Benz/C-Class",

  // Mercedes-Benz E-Class
  "Mercedes-Benz/E 350": "Mercedes-Benz/E-Class",
  "Mercedes-Benz/E 200": "Mercedes-Benz/E-Class",
  "Mercedes-Benz/E 300": "Mercedes-Benz/E-Class",
  "Mercedes-Benz/E300": "Mercedes-Benz/E-Class",
  "Mercedes-Benz/E 400": "Mercedes-Benz/E-Class",
  "Mercedes-Benz/E 220": "Mercedes-Benz/E-Class",
  "Mercedes-Benz/E 280": "Mercedes-Benz/E-Class",
  "Mercedes-Benz/E55 AMG": "Mercedes-Benz/E-Class",
  "Mercedes-Benz/E220 CDI": "Mercedes-Benz/E-Class",
  "Mercedes-Benz/E 220 CDI BLUEMATUC": "Mercedes-Benz/E-Class",
  "Mercedes-Benz/E-Class (E350)": "Mercedes-Benz/E-Class",
  "Mercedes-Benz/E-class cab.": "Mercedes-Benz/E-Class",
  "Mercedes-Benz/W212/E300": "Mercedes-Benz/E-Class",
  "Mercedes-Benz/300 e class": "Mercedes-Benz/E-Class",
  "Mercedes-Benz/w207": "Mercedes-Benz/E-Class",

  // Mercedes-Benz A-Class
  "Mercedes-Benz/A 180": "Mercedes-Benz/A-Class",
  "Mercedes-Benz/A 160": "Mercedes-Benz/A-Class",
  "Mercedes-Benz/A 200": "Mercedes-Benz/A-Class",
  "Mercedes-Benz/A 250 e": "Mercedes-Benz/A-Class",
  "Mercedes-Benz/A45": "Mercedes-Benz/A-Class",
  "Mercedes-Benz/AMG A 45": "Mercedes-Benz/A-Class",
  "Mercedes-Benz/A 45 AMG 4matic": "Mercedes-Benz/A-Class",
  "Mercedes-Benz/A-Klasse": "Mercedes-Benz/A-Class",

  // Mercedes-Benz B-Class
  "Mercedes-Benz/B 200": "Mercedes-Benz/B-Class",

  // Mercedes-Benz GLA-Class
  "Mercedes-Benz/GLA 220": "Mercedes-Benz/GLA-Class",
  "Mercedes-Benz/GLA 250": "Mercedes-Benz/GLA-Class",
  "Mercedes-Benz/GLA 250e": "Mercedes-Benz/GLA-Class",
  "Mercedes-Benz/GLA 180": "Mercedes-Benz/GLA-Class",
  "Mercedes-Benz/GLA200d": "Mercedes-Benz/GLA-Class",
  "Mercedes-Benz/GLA": "Mercedes-Benz/GLA-Class",

  // Mercedes-Benz GLB-Class
  "Mercedes-Benz/GLB 250": "Mercedes-Benz/GLB-Class",
  "Mercedes-Benz/GLB 200": "Mercedes-Benz/GLB-Class",
  "Mercedes-Benz/GLB 220": "Mercedes-Benz/GLB-Class",
  "Mercedes-Benz/GLB 200d Automatic": "Mercedes-Benz/GLB-Class",
  "Mercedes-Benz/GLb": "Mercedes-Benz/GLB-Class",
  "Mercedes-Benz/GLB": "Mercedes-Benz/GLB-Class",

  // Mercedes-Benz GLC-Class
  "Mercedes-Benz/GLC 300": "Mercedes-Benz/GLC-Class",
  "Mercedes-Benz/GLC 220": "Mercedes-Benz/GLC-Class",
  "Mercedes-Benz/GLC 300e": "Mercedes-Benz/GLC-Class",
  "Mercedes-Benz/GLC": "Mercedes-Benz/GLC-Class",

  // Mercedes-Benz GLE-Class
  "Mercedes-Benz/GLE53 4matic": "Mercedes-Benz/GLE-Class",
  "Mercedes-Benz/Gle 53": "Mercedes-Benz/GLE-Class",
  "Mercedes-Benz/GLE 350": "Mercedes-Benz/GLE-Class",
  "Mercedes-Benz/GLE 43 AMG Coupe": "Mercedes-Benz/GLE-Class",
  "Mercedes-Benz/GLE 53 AMG Coupe": "Mercedes-Benz/GLE-Class",

  // Mercedes-Benz GLS-Class
  "Mercedes-Benz/GL 350": "Mercedes-Benz/GLS-Class",

  // Mercedes-Benz GLK-Class
  "Mercedes-Benz/GLK 220": "Mercedes-Benz/GLK-Class",

  // Mercedes-Benz CLA-Class
  "Mercedes-Benz/CLA 200": "Mercedes-Benz/CLA-Class",
  "Mercedes-Benz/CLA 180": "Mercedes-Benz/CLA-Class",
  "Mercedes-Benz/CLA 250": "Mercedes-Benz/CLA-Class",
  "Mercedes-Benz/CLA 220": "Mercedes-Benz/CLA-Class",
  "Mercedes-Benz/Cla 200d": "Mercedes-Benz/CLA-Class",

  // Mercedes-Benz CLS-Class
  "Mercedes-Benz/CLS500": "Mercedes-Benz/CLS-Class",
  "Mercedes-Benz/CLS 320 CDI": "Mercedes-Benz/CLS-Class",
  "Mercedes-Benz/CLS": "Mercedes-Benz/CLS-Class",

  // Mercedes-Benz CLK-Class
  "Mercedes-Benz/CLK": "Mercedes-Benz/CLK-Class",
  "Mercedes-Benz/CLK 280": "Mercedes-Benz/CLK-Class",

  // Mercedes-Benz S-Class
  "Mercedes-Benz/S 500": "Mercedes-Benz/S-Class",
  "Mercedes-Benz/S 350 L GR": "Mercedes-Benz/S-Class",
  "Mercedes-Benz/S 320": "Mercedes-Benz/S-Class",

  // Mercedes-Benz M-Class
  "Mercedes-Benz/ML 250": "Mercedes-Benz/M-Class",
  "Mercedes-Benz/Ml63": "Mercedes-Benz/M-Class",

  // Mercedes-Benz G-Class
  "Mercedes-Benz/G63": "Mercedes-Benz/G-Class",
  "Mercedes-Benz/G 63 AMG": "Mercedes-Benz/G-Class",

  // Mercedes-Benz EQ models
  "Mercedes-Benz/EQE350": "Mercedes-Benz/EQE",
  "Mercedes-Benz/EQE 43": "Mercedes-Benz/EQE",
  "Mercedes-Benz/Eqa250+": "Mercedes-Benz/EQA",
  "Mercedes-Benz/EQC 400": "Mercedes-Benz/EQC",

  // Mercedes-Benz misc
  "Mercedes-Benz/Sedan": anonymousName,
  "Mercedes-Benz/2019": anonymousName,
  "Mercedes-Benz/300-Class": "Mercedes-Benz/E-Class",
  "Mercedes-Benz/400-Class": "Mercedes-Benz/S-Class",
  "Mercedes-Benz/560-Class": "Mercedes-Benz/S-Class",
  "Mercedes-Benz/slc": "Mercedes-Benz/SLC-Class",
  "Mercedes-Benz/SLK Roadster": "Mercedes-Benz/SLK-Class",
  "Mercedes-Benz/Classe V 300d": "Mercedes-Benz/V-Class",

  // Lexus consolidation
  "Lexus/ES 350": "Lexus/ES",
  "Lexus/ES 250": "Lexus/ES",
  "Lexus/ES 300h": "Lexus/ES",
  "Lexus/ES 300": "Lexus/ES",
  "Lexus/ES 330": "Lexus/ES",
  "Lexus/RX 350": "Lexus/RX",
  "Lexus/RX 450h": "Lexus/RX",
  "Lexus/RX 500h": "Lexus/RX",
  "Lexus/RX 350h": "Lexus/RX",
  "Lexus/RX 300": "Lexus/RX",
  "Lexus/IS 300": "Lexus/IS",
  "Lexus/IS 350": "Lexus/IS",
  "Lexus/IS 250": "Lexus/IS",
  "Lexus/IS 500": "Lexus/IS",
  "Lexus/IS 300h": "Lexus/IS",
  "Lexus/IS 200t": "Lexus/IS",
  "Lexus/IS 350 F sport": "Lexus/IS",
  "Lexus/IS 300 Hybrid": "Lexus/IS",
  "Lexus/GS 350": "Lexus/GS",
  "Lexus/GS 300": "Lexus/GS",
  "Lexus/GS F": "Lexus/GS",
  "Lexus/GX 460": "Lexus/GX",
  "Lexus/GX 470": "Lexus/GX",
  "Lexus/LX 570": "Lexus/LX",
  "Lexus/LX 600": "Lexus/LX",
  "Lexus/LX 470": "Lexus/LX",
  "Lexus/NX 350": "Lexus/NX",
  "Lexus/NX 200t": "Lexus/NX",
  "Lexus/NX 350h": "Lexus/NX",
  "Lexus/NX 300": "Lexus/NX",
  "Lexus/NX 300h": "Lexus/NX",
  "Lexus/NX 250": "Lexus/NX",
  "Lexus/CT 200h": "Lexus/CT",
  "Lexus/CT 200": "Lexus/CT",
  "Lexus/UX 250h": "Lexus/UX",
  "Lexus/UX 250": "Lexus/UX",
  "Lexus/HS 250h": "Lexus/HS",
  "Lexus/LC 500": "Lexus/LC",
  "Lexus/LS 500": "Lexus/LS",
  "Lexus/LS 400": "Lexus/LS",
  "Lexus/LS 430": "Lexus/LS",
  "Lexus/LS 460": "Lexus/LS",
  "Lexus/RC 350": "Lexus/RC",
  "Lexus/RZ 450e": "Lexus/RZ",
  "Lexus/2023": anonymousName,

  // Audi consolidation
  "Audi/A6 Avant 40TDI": "Audi/A6",
  "Audi/A6 C4": "Audi/A6",
  "Audi/A5 sportback": "Audi/A5",
  "Audi/A4 Avant": "Audi/A4",
  "Audi/A1 sportback": "Audi/A1",
  "Audi/A3 sportback": "Audi/A3",
  "Audi/A3  TFSI e": "Audi/A3",
  "Audi/TT 8J": "Audi/TT",
  "Audi/Q3 Sb": "Audi/Q3",
  "Audi/Q5 hyb Vincenzo": "Audi/Q5",
  "Audi/Q5 50TFSI-e": "Audi/Q5",
  "Audi/Q6 Quattro": "Audi/Q6",
  "Audi/Audi A5": "Audi/A5",
  "Audi/GR86": anonymousName,
  "Audi/C400": anonymousName,
  "Audi/2024": anonymousName,

  // Porsche consolidation
  "Porsche/Cayenne S": "Porsche/Cayenne",
  "Porsche/Cayenne S E": "Porsche/Cayenne",
  "Porsche/Cayenne E-Hybrid": "Porsche/Cayenne",
  "Porsche/Cayman S": "Porsche/Cayman",
  "Porsche/911 Carrera": "Porsche/911",
  "Porsche/Taycan 4": "Porsche/Taycan",
  "Porsche/Turbo S": "Porsche/911",
  "Porsche/986": "Porsche/Boxster",

  // Nissan consolidation
  "Nissan/Patrol Platinum": "Nissan/Patrol",
  "Nissan/Patrol Y62 V8": "Nissan/Patrol",
  "Nissan/370Z NISMO": "Nissan/370Z",
  "Nissan/Nissan": anonymousName,
  "Nissan patrol/Patrol": "Nissan/Patrol",

  // Toyota consolidation
  "Toyota/Land Cruiser LC300": "Toyota/Land Cruiser",
  "Toyota/Lc300": "Toyota/Land Cruiser",
  "Toyota/LC300": "Toyota/Land Cruiser",
  "Toyota/LC 300": "Toyota/Land Cruiser",
  "Toyota/GXR": "Toyota/Land Cruiser",
  "Toyota/Landcruiser Hybrid": "Toyota/Land Cruiser",
  "Toyota/Tundr": "Toyota/Tundra",
  "Toyota/Korla": "Toyota/Corolla",
  "Toyota/Corolla touring sport": "Toyota/Corolla",
  "Toyota/Corolla SE": "Toyota/Corolla",
  "Toyota/AXVA80L-AEZDBD": anonymousName,
  "Toyota/MR0DB9CD7N4989236": anonymousName,
  "Toyota/HILUX 150 SER": "Toyota/Hilux",
  "Toyota/E": anonymousName,
  "Toyota/IS": anonymousName,
  "Toyota/Idk": anonymousName,
  "Toyota/2024": anonymousName,
  "Toyota/2023": anonymousName,
  "Toyota/Fortuner 2.4 4x2": "Toyota/Fortuner",
  "Toyota/Fortuner Legender": "Toyota/Fortuner",
  "Toyota/Yaris Hibryd": "Toyota/Yaris",
  "Toyota/Hycross HYBRID ZX": "Toyota/Hyryder",
  "Toyota/RAV4 Prime Plugin Hybrid": "Toyota/RAV4 Prime",
  "Toyota/Innova hycross": "Toyota/Innova",
  "Toyota/Innova Zenix": "Toyota/Innova",
  "Toyota/Innova Crysta": "Toyota/Innova",

  // VW/Volkswagen consolidation
  "VW/Passat": "Volkswagen/Passat",
  "VW/GOLF": "Volkswagen/Golf",
  "VW/Golf R": "Volkswagen/Golf",
  "VW/ID.4": "Volkswagen/ID.4",
  "Vw/Tiguan": "Volkswagen/Tiguan",
  "Vw/Hw": anonymousName,
  "Volkswagen/Golf GTI": "Volkswagen/Golf",
  "Volkswagen/Golf GTE": "Volkswagen/Golf",
  "Volkswagen/Golf R": "Volkswagen/Golf",
  "Volkswagen/GOLF R": "Volkswagen/Golf",
  "Volkswagen/Golf 5": "Volkswagen/Golf",
  "Volkswagen/Golf 6": "Volkswagen/Golf",
  "Volkswagen/Golf 7": "Volkswagen/Golf",
  "Volkswagen/Golf 8": "Volkswagen/Golf",
  "Volkswagen/Golf Mk4": "Volkswagen/Golf",
  "Volkswagen/Golf Variant": "Volkswagen/Golf",
  "Volkswagen/Jetta GLI": "Volkswagen/Jetta",
  "Volkswagen/Polo GTI": "Volkswagen/Polo",
  "Volkswagen/Passat cc": "Volkswagen/Passat",
  "Volkswagen/Passat B8": "Volkswagen/Passat",
  "Volkswagen/ID.7 Tourer": "Volkswagen/ID.7",
  "Volkswagen/ID.7 Pro": "Volkswagen/ID.7",
  "Volkswagen/T-Roc Cabriolet": "Volkswagen/T-Roc",
  "opel/corsa": "Opel/Corsa",

  // Ford consolidation
  "Ford/Ranger Raptor": "Ford/Ranger",
  "Ford/Ranger wildtrak": "Ford/Ranger",
  "Ford/F-150 Lightning": "Ford/F-150",
  "Ford/Raptor": "Ford/F-150",
  "Ford/Shelby GT350": "Ford/Mustang",
  "Ford Taurus/Taurus": "Ford/Taurus",
  "Ford/Xlt": anonymousName,
  "Ford/2018": anonymousName,
  "Ford/TITANIUM TERRITORY": "Ford/Territory",
  "Ford/Mach E": "Ford/Mustang Mach-E",
  "Ford/Transit custom": "Ford/Transit",

  // Honda consolidation
  "Honda/civic TYPE R": "Honda/Civic",
  "Honda/Civic Type-R": "Honda/Civic",
  "Honda/Civic Type R": "Honda/Civic",
  "Honda/Civic Hatchback": "Honda/Civic",
  "Honda/Civic del Sol": "Honda/Civic",
  "Honda/Honda city gm2": "Honda/City",
  "Honda/City GN2": "Honda/City",
  "Honda/Azera": "Hyundai/Azera",
  "Honda/Z rv": "Honda/ZR-V",
  "Honda/Exl": anonymousName,
  "Honda/2024": anonymousName,
  "Honda/2022": anonymousName,

  // Hyundai consolidation
  "Hyundai/Elentra": "Hyundai/Elantra",
  "Hyundai/Tuscon": "Hyundai/Tucson",
  "Hyundai/Krita": "Hyundai/Creta",
  "Hyundai/Full": anonymousName,
  "Hyundai/Sedan": anonymousName,
  "Hyundai/Avanti": "Hyundai/Elantra",
  "Hyundai/Avante": "Hyundai/Elantra",
  "Hyundai/Avante S": "Hyundai/Elantra",
  "Hyundai/i30 N": "Hyundai/i30",
  "Hyundai/i30 Sedan": "Hyundai/i30",
  "Hyundai/I30 sedan": "Hyundai/i30",
  "Hyundai/Veloster N": "Hyundai/Veloster",
  "Hyundai/Kona SX2": "Hyundai/Kona",
  "Huyndai/Azera": "Hyundai/Azera",
  "Hyundia /Sonata": "Hyundai/Sonata",
  "Hyundia /Ioniq 5": "Hyundai/IONIQ 5",
  "S O N A T A/2025": "Hyundai/Sonata",

  // Kia consolidation
  "Kia/Sportage gt line S": "Kia/Sportage",
  "Kia/Sportage 4": "Kia/Sportage",
  "Kia/Sportage 3": "Kia/Sportage",
  "Kia/Sportage PHEV": "Kia/Sportage",
  "Kia/Cerato K3": "Kia/Cerato",
  "Kia/Kia K5 2023": "Kia/K5",
  "Kia/Rio 3": "Kia/Rio",
  "Kia/Rio 4": "Kia/Rio",
  "Kia/Niro 2": "Kia/Niro",
  "Kia/Niro 3": "Kia/Niro",
  "Kia/Niro 4": "Kia/Niro",
  "Kia/Niro HEV": "Kia/Niro",
  "Kia/Niro PHAEV": "Kia/Niro",
  "Kia/E-Niro": "Kia/Niro EV",
  "Kia/e-Niro": "Kia/Niro EV",
  "Kia/Optima 2": "Kia/Optima",
  "Kia/Ceed CD": "Kia/Ceed",
  "Kia/Pro Ceed 2": "Kia/ProCeed",
  "Kia/Pro Ceed": "Kia/ProCeed",
  "Kia/Carens 3": "Kia/Carens",
  "Kia/Picanto 1": "Kia/Picanto",
  "Kia/Picanto 3": "Kia/Picanto",
  "Kia/Picanto 1.2": "Kia/Picanto",
  "Kia/Carnival II": "Kia/Carnival",
  "Kia/Carnival / Sedona": "Kia/Carnival",
  "Kia/Siltos": "Kia/Seltos",
  "Kia/MAR/2025": anonymousName,
  "Kia/2023": anonymousName,
  "Kia/2022": anonymousName,
  "Kia/E.g": anonymousName,

  // Land Rover consolidation
  "Land Rover/Defender X": "Land Rover/Defender",
  "Land Rover/Defender 9": "Land Rover/Defender",
  "Land Rover/Defender 110": "Land Rover/Defender",
  "Land Rover/defender 110": "Land Rover/Defender",
  "Land Rover/Defender 90": "Land Rover/Defender",
  "Land Rover/Defender P400": "Land Rover/Defender",
  "Land Rover/Defender X-dynamic HSE": "Land Rover/Defender",
  "Land Rover/Defender Z": "Land Rover/Defender",
  "Land Rover/Denfender": "Land Rover/Defender",
  "Land Rover/110": "Land Rover/Defender",
  "Land Rover/HSE": "Land Rover/Range Rover",
  "Land Rover/Se": "Land Rover/Range Rover",
  "Land Rover/Autobiography": "Land Rover/Range Rover",
  "Land Rover/Evoque": "Land Rover/Range Rover Evoque",
  "Land Rover/X 6": anonymousName,
  "Land Rover/4e": anonymousName,
  "Land Rover/2023": anonymousName,
  "Land Rover/2024": anonymousName,

  // Jeep consolidation
  "Jeep/Wrangler 4xe": "Jeep/Wrangler",
  "Jeep/Wrangler JK": "Jeep/Wrangler",
  "Jeep/Wrangler Rubicon": "Jeep/Wrangler",
  "Jeep/Wrangler Rubicon jl 4xe": "Jeep/Wrangler",
  "Jeep/Grand Cherokee L": "Jeep/Grand Cherokee",
  "Jeep/Renegade Sport": "Jeep/Renegade",
  "Jeep/Avenger 1.2 mhev": "Jeep/Avenger",

  // Changan consolidation
  "Changan/Uni t": "Changan/UNI-T",
  "Changan/Uni S": "Changan/UNI-S",
  "Changan/Uni-s": "Changan/UNI-S",
  "Changan/Uni-k": "Changan/UNI-K",
  "Changan/Uni-K": "Changan/UNI-K",
  "Changan/Cs95": "Changan/CS95",
  "Changan/Uni V": "Changan/UNI-V",
  "Changan/Edou plus": "Changan/Eado Plus",
  "Changan/Edo plus": "Changan/Eado Plus",
  "Changan/Eado plus": "Changan/Eado Plus",
  "Changan/CS35 Plus 1.4 Turbo": "Changan/CS35 Plus",

  // Chery consolidation
  "Chery/Tiggo 7 pro": "Chery/Tiggo 7 Pro",
  "Chery/Tiggo 4 pro": "Chery/Tiggo 4 Pro",
  "Chery/Arrizo8": "Chery/Arrizo 8",
  "CHERY/ARRIZO 8": "Chery/Arrizo 8",
  "CHERY/Arrizo 8": "Chery/Arrizo 8",
  "Chery/7 pro max": "Chery/Tiggo 7 Pro Max",
  "chery/jetour": "Jetour/T2",
  "Chery automobile co. Ltd/Jaecoo 7": "Jaecoo/J7",
  "Chery/Spranza": anonymousName,

  // Misc typos and consolidations
  "renoult/Clio 4": "Renault/Clio",
  "Renault/Clio IV": "Renault/Clio",
  "Renault/clio4": "Renault/Clio",
  "Renault/Clio5": "Renault/Clio",
  "Renault/Clio 4": "Renault/Clio",
  "Renault/Clio 5": "Renault/Clio",
  "Renault/Clio v": "Renault/Clio",
  "Renault/Clio V": "Renault/Clio",
  "Renault/Meagne": "Renault/Megane",
  "Seaf/Leon": "Seat/Leon",
  "Seat/Leon ST": "Seat/Leon",
  "Seat/Leon SC": "Seat/Leon",
  "Seat/Leon 5F": "Seat/Leon",
  "VOLVOv/XC60": "Volvo/XC60",
  "GMC/G m c": "GMC/Sierra",
  "GMC/SIERRA": "GMC/Sierra",
  "GMC/At4": "GMC/Sierra",
  "Mazda/Mazda 6": "Mazda/Mazda6",
  "Mazda/mazda 6": "Mazda/Mazda6",
  "Mazda/MAZDA 6": "Mazda/Mazda6",
  "Mazda/MAZDA6": "Mazda/Mazda6",
  "Mazda/Mazda 3": "Mazda/Mazda3",
  "Mazda/Mazda 2": "Mazda/Mazda2",
  "Mazda/Sedan": anonymousName,
  "Mazda/Cx-60": "Mazda/CX-60",
  "Haval/H6 GT": "Haval/H6",
  "Haval/Jolion 1.5T luxury": "Haval/Jolion",
  "Haval/Jolion HEV": "Haval/Jolion",
  "GWM/Haval H6": "Haval/H6",
  "GWM/HAVAL": "Haval/H6",
  "Great Wall Motor /HAVAL JOLION": "GWM/Haval Jolion",
  "Great Wall/Tank 300": "GWM/Tank 300",
  "Great Wall/TANK300": "GWM/Tank 300",
  "Gwm/Tank 300": "GWM/Tank 300",
  "Peugeot/308 GT": "Peugeot/308",
  "Peugeot/308 SW": "Peugeot/308",
  "Peugeot/308sw": "Peugeot/308",
  "Peugeot/308 Hybrid": "Peugeot/308",
  "Peugeot/Boxer 335": "Peugeot/Boxer",
  "Peugeot/208 GTI": "Peugeot/208",
  "Peugeot/E2008 GT": "Peugeot/e-2008",
  "Peugeot/E2008": "Peugeot/e-2008",
  "Peugeot/E-2008": "Peugeot/e-2008",
  "Peugeot/508 plug-in hybrid": "Peugeot/508",
  "MINI/Cooper S": "MINI/Cooper",
  "MINI/Cooper s": "MINI/Cooper",
  "MINI/Cooper SE": "MINI/Cooper",
  "MINI/Cooper C": "MINI/Cooper",
  "MINI/Cooper Diesel": "MINI/Cooper",
  "MINI/Cooper Countryman": "MINI/Countryman",
  "MINI/Cooper Clubman": "MINI/Clubman",
  "MINI/Mini": "MINI/Cooper",
  "MINI/JCW": "MINI/John Cooper Works",
  "Cadillac/Rav4": "Toyota/RAV4",
  "Cadillac/Camry": "Toyota/Camry",
  "INFINITI/G37": "INFINITI/G",
  "INFINITI/G35": "INFINITI/G",
  "INFINITI/G Sedan": "INFINITI/G",
  "INFINITI/M35": "INFINITI/M",
  "INFINITI/M37": "INFINITI/M",
  "Geely/Emagrandi": "Geely/Emgrand",
  "Geely/preface": "Geely/Preface",
  "Geely/Monjato": "Geely/Monjaro",
  "GEELY/Monjaro": "Geely/Monjaro",
  "Chevrolet/2019": anonymousName,
  "Chevrolet/6.0": anonymousName,
  "Chevorlet /Grove": "Chevrolet/Groove",
  "Chevy/Nova": "Chevrolet/Nova",
  "Polestar/Polestar 3": "Polestar/3",
  "Dodge/Ram 1500": "Ram/1500",
  "Dodge/Ram": "Ram/1500",
  "Dodge/RAM 150": "Ram/1500",
  "Dodge/1500": "Ram/1500",
  "GAC Ambao/athlete": anonymousName,
  "Gac/Empaw": "GAC/Empow",
  "Hhgfggv/Gghggh": anonymousName,
  "Ghjb/Fhhg": anonymousName,
  "cv/cv": anonymousName,
  "r/r": anonymousName,
  "G/G": anonymousName,
  "Koria/2025": anonymousName,

  // Subaru consolidation
  "Subaru/XV Crosstrek": "Subaru/Crosstrek",
  "Subaru/Impreza WRX": "Subaru/WRX",
  "Subaru/B9 Tribeca": "Subaru/Tribeca",
  "Subaru/STI S209": "Subaru/WRX STI",

  // Volvo consolidation
  "Volvo/XC40 Recharge": "Volvo/XC40",
  "Volvo/XC40 T4": "Volvo/XC40",
  "Volvo/C40 Recharge": "Volvo/C40",
  "Volvo/S60 PHEV": "Volvo/S60",
  "Volvo/V90 Cross Country": "Volvo/V90",
  "Volvo/V40 CC 1.6T": "Volvo/V40",
  "Volvo/EX40": "Volvo/EX30",
  "Volvo/Unknown": anonymousName,

  // Genesis consolidation
  "Genesis/Electrified GV70": "Genesis/GV70",

  // MINI consolidation
  "MINI/Hardtop": "MINI/Cooper",
  "MINI/Hardtop SE": "MINI/Cooper",
  "MINI/Hatch": "MINI/Cooper",
  "MINI/One": "MINI/Cooper",
  "MINI/i3s": "BMW/i3",

  // Acura consolidation - ILX remains separate from Integra (different platforms)

  // Jaguar consolidation
  "Jaguar/F-TYPE": "Jaguar/F-Type",

  // Skoda consolidation
  "Skoda/Fabia 4": "Skoda/Fabia",
  "Skoda/Octavia scout": "Skoda/Octavia",
  "Skoda/Octavia Break iV": "Skoda/Octavia",
  "Skoda/Superb 3V": "Skoda/Superb",
  "Skoda/ENYAQ 85": "Skoda/Enyaq",
  "Skoda/Kodiaq mk2": "Skoda/Kodiaq",

  // Alfa Romeo consolidation
  "Alfa Romeo/Giulia (952)": "Alfa Romeo/Giulia",

  // Seat/Cupra consolidation
  "Seat/Exeo ST": "Seat/Exeo",
  "Seat/Ibisa": "Seat/Ibiza",
  "Cupra/Forementor": "Cupra/Formentor",

  // Citroen consolidation
  "Citroen/C4 Grand Picasso": "Citroen/C4 Picasso",
  "Citroen/C4 plus hybrid": "Citroen/C4",
  "Citroen/C5 aircross": "Citroen/C5 Aircross",
  "Citroen/Tupe commerciale": anonymousName,

  // Dacia consolidation
  "Dacia/Sandero II": "Dacia/Sandero",
  "Dacia/Sandero III": "Dacia/Sandero",
  "Dacia/Duster II": "Dacia/Duster",
  "Dacia/Duster III": "Dacia/Duster",
  "Dacia/Logan 1": "Dacia/Logan",

  // Fiat consolidation
  "FIAT/500 abarth": "Abarth/500",
  "FIAT/Fiat500X": "FIAT/500X",
  "FIAT/600 Hybrid": "FIAT/600",

  // BYD consolidation
  "BYD/DOLPHIN": "BYD/Dolphin",
  "BYD/Song plus": "BYD/Song Plus",

  // Misc additional typos
  "Rox/01": anonymousName,
  "Jetour/Jetour": "Jetour/T2",
  "Jetour/SQR6480F26CA": anonymousName,
  "Jetour/X70 plus": "Jetour/X70",
  "smart/fortwo": "Smart/Fortwo",
  "smart/1": "Smart/#1",
  "faw/B70": "FAW/B70",
  "HMC/Staria": "Hyundai/Staria",
  "HongQi/Ousado": "Hongqi/E-HS9",
  "ZEEKR/Tugella": "Zeekr/001",
  "AION/UT": "GAC Aion/Y",
  "EVO/EVO 7": "Mitsubishi/Lancer Evolution",
  "DR/5.0 S3": "DR/5.0",
  "Talaria/XXX": anonymousName,
  "KTM/RC": "KTM/RC 390",
  "KTM/Duke": "KTM/Duke 390",
  "KTM/Duke 390": "KTM/390 Duke",
  "Kawasaki/Ninja 650": "Kawasaki/Ninja",
  "Yamaha/Nmax": "Yamaha/NMAX",
  "HARLEY-DAVIDSON/FLTRX / Road Glide": "Harley-Davidson/Road Glide",
  "HARLEY-DAVIDSON/Street Glide ST": "Harley-Davidson/Street Glide",
  "HARLEY-DAVIDSON/Electra Glide Ultra Classic": "Harley-Davidson/Electra Glide",
  "Harley Davidsion /Road Glide": "Harley-Davidson/Road Glide",
  "Scania/R500": "Scania/R-Series",

  // More gibberish/invalid entries
  "ALL ABOUT TRAILERS/All About Trailers": anonymousName,
  "KOUNTRY AIRE/Kountry Aire Trailer": anonymousName,
  "STANDARD IRON/Standard Iron": anonymousName,
  "BEIQI FOTON MOTOR / BEIJING BUS BRANCH/Passenger Car": anonymousName,
  "COBRA INDUSTRIES/Jeep Cherokee": "Jeep/Cherokee",
  "COBRA INDUSTRIES/Jeep": "Jeep/Wrangler",

  // Buick consolidation
  "Buick/Regal TourX": "Buick/Regal",

  // Chrysler consolidation
  "Chrysler/300C": "Chrysler/300",
  "Chrysler/Delta SE": "Chrysler/Delta",
  "Chrysler/Pacifica Hybrid": "Chrysler/Pacifica",
  "Chrysler/Town and Country": "Chrysler/Town & Country",

  // Ram consolidation
  "Ram/ProMaster Cargo Van": "Ram/ProMaster",

  // Chevrolet additional
  "Chevrolet/Corvette Stingray": "Chevrolet/Corvette",
  "Chevrolet/Silverado 2500": "Chevrolet/Silverado 2500HD",
  "Chevrolet/Silverado 3500": "Chevrolet/Silverado 3500HD",
  "Chevrolet/2500hd": "Chevrolet/Silverado 2500HD",
  "Chevrolet/Pontiac": anonymousName,
  "Chevrolet/Premier": anonymousName,
  "Chevrolet/Bolt": "Chevrolet/Bolt EV",

  // GMC additional
  "GMC/Sierra Limited": "GMC/Sierra 1500",
  "GMC/Sierra 1500 Limited": "GMC/Sierra 1500",
  "GMC/Yukon Denali": "GMC/Yukon",
  "GMC/Yukon XL": "GMC/Yukon",

  // Lincoln additional
  "Lincoln/MKZ": "Lincoln/Continental",
  "Lincoln/MKX": "Lincoln/Nautilus",

  // Mitsubishi additional
  "Mitsubishi/Montero": "Mitsubishi/Pajero",
  "Mitsubishi/Montero Sport": "Mitsubishi/Pajero Sport",
  "Mitsubishi/Lancer Evolution": "Mitsubishi/Lancer",
  "Mitsubishi/Pajero Mini": "Mitsubishi/Pajero",

  // Dodge additional
  "Dodge/Daytona": "Dodge/Charger",

  // Pontiac
  "Pontiac/Safari": "Pontiac/Grand Safari",

  // Holden
  "Holden/Calais V": "Holden/Commodore",

  // Proton/Perodua
  "Proton/Suprima S": "Proton/Suprima",

  // Maruti Suzuki
  "Maruti suzuki/S cross": "Maruti Suzuki/S-Cross",

  // Suzuki additional
  "Suzuki/V-Strom DL250": "Suzuki/V-Strom",
  "Suzuki/Jimny XL": "Suzuki/Jimny",


  // Dongfeng
  "Dongfeng/Aeolus y3": "Dongfeng/Aeolus",
  "Dongfeng /A60 Max": "Dongfeng/A60",

  // GAC additional
  "GAC Motor/GS3": "GAC/GS3",
  "GAC/GS3 EMZOOM": "GAC/GS3",
  "GAC/GS3 Emzoom R-Style": "GAC/GS3",
  "GAC/GS3 Power": "GAC/GS3",
  "GAC/EMZOOM": "GAC/Empow",

  // Geely additional
  "Geely/Atlas Pro": "Geely/Atlas",

  // Xiaomi/VinFast
  "Xiaomi/Su7": "Xiaomi/SU7",
  "VinFast/VF 8": "VinFast/VF8",

  // Maserati
  "Maserati/Ghibli SQ4": "Maserati/Ghibli",

  // Ferrari/Bentley
  "Ferrari/812 Superfast": "Ferrari/812",
  "Bentley/Continental": "Bentley/Continental GT",

  // Lotus
  "Lotus/Evora GT": "Lotus/Evora",

  // DS
  "DS/DS7": "DS/DS 7",
  "DS/4": "DS/DS 4",

  // Ligier
  "Ligier/JS": "Ligier/JS50",

  // Seres
  "Seres/Max 5": "Seres/5",

  // Daewoo
  "Daewoo/Cruze": "Chevrolet/Cruze",

  // LDV
  "LDV/T60 Max": "LDV/T60",

  // AM General
  "AM General/Hummer": "Hummer/H2",
  "HUMMER/H3": "Hummer/H3",


  // OPEL additional
  "OPEL/CROSSLAND X": "OPEL/Crossland",
  "OPEL/Crossland X": "OPEL/Crossland",
  "OPEL/Astra K": "OPEL/Astra",
  "OPEL/Astra H": "OPEL/Astra",
  "OPEL/Grandland X": "OPEL/Grandland",
  "Opel/Astra": "OPEL/Astra",
  "Opel/Mokka": "OPEL/Mokka",

  // Vauxhall additional
  "Vauxhall/Astra": "Vauxhall-Opel/Astra",
  "Vauxhall/Insignia": "Vauxhall-Opel/Insignia",

  // INEOS
  "INEOS/Grenadier": "Ineos/Grenadier",

  // Great Wall/GWM additional
  "Great Wall/Steed": "GWM/Steed",
  "Great Wall/Ute": "GWM/Ute",
  "GWM/Tank": "GWM/Tank 300",

  // BMW X-series consolidation
  "BMW/X5 eDrive": "BMW/X5",
  "BMW/X5 45edrive": "BMW/X5",
  "BMW/X4 M": "BMW/X4",
  "BMW/X4 M40i": "BMW/X4",
  "BMW/X3 M": "BMW/X3",
  "BMW/X3 M40I": "BMW/X3",
  "BMW/X3 M40d": "BMW/X3",
  "BMW/X2 M 20i": "BMW/X2",
  "BMW/iX45": "BMW/iX",
  "BMW/Ix40": "BMW/iX",
  "BMW/i4 M50": "BMW/i4",
  "BMW/Elise": anonymousName,

  // Additional VW corrections
  "Volkswagen/GOLF CITY": "Volkswagen/Golf",
  "Volkswagen/GLI": "Volkswagen/Jetta",
  "Volkswagen/R32": "Volkswagen/Golf",
  "Volkswagen/ID.Buzz": "Volkswagen/ID. Buzz",

  // Audi e-tron consolidation
  "Audi/Q4 Sportback e-tron": "Audi/Q4 e-tron",
  "Audi/S6 Avant e-tron": "Audi/A6 e-tron",
  "Audi/SQ6 e-tron": "Audi/Q6 e-tron",
  "Audi/Q7 e-tron": "Audi/Q7",
  "Audi/RS Q8": "Audi/Q8",
  "Audi/allroad quattro": "Audi/A6 allroad",
  "Audi/allroad": "Audi/A6 allroad",

  // Additional year/invalid entries
  "Eagle/Renault Captur Techno GPL": "Renault/Captur",
  "Mazda/Mazdaspeed MX-5 Miata": "Mazda/MX-5",
  "Mazda/Mazda2 hybrid": "Mazda/Mazda2",
  "Renault/Sandero": "Dacia/Sandero",
  "Renault/Stepaway": "Dacia/Sandero Stepway",
  "Renault/New Captur": "Renault/Captur",
  "Renault/Zoe INTENS (Selection) R135": "Renault/Zoe",

  // Lincoln corrections
  "Lincoln/MKZ": "Lincoln/Zephyr",

  // Toyota additional
  "Toyota/Highlander Hybrid": "Toyota/Highlander",
  "Toyota/Grand Highlander Hybrid": "Toyota/Grand Highlander",
  "Toyota/Crown Hybrid": "Toyota/Crown",
  "Toyota/Crown Signia": "Toyota/Crown",
  "Toyota/Prius Prime Plugin": "Toyota/Prius Prime",
  "Toyota/Prius Plug-in": "Toyota/Prius Prime",
  "Toyota/Prius v": "Toyota/Prius",
  "Toyota/Avalon Hybrid": "Toyota/Avalon",
  "Toyota/Yaris Cross Hybrid": "Toyota/Yaris Cross",
  "Toyota/Camry Solara": "Toyota/Solara",
  "Toyota/GR Yaris": "Toyota/Yaris",
  "Toyota/Auris Touring Sport": "Toyota/Auris",
  "Toyota/Kluger": "Toyota/Highlander",

  // More Lexus
  "Lexus/RX 350": "Lexus/RX",

  // Additional Porsche
  "Porsche/CAYMAN": "Porsche/Cayman",
  "Porsche/Macan Electric": "Porsche/Macan",

  // More Honda
  "Honda/CR-V Hybrid": "Honda/CR-V",
  "Honda/Fit EV": "Honda/Fit",
  "Honda/Shuttle Hybrid Z": "Honda/Shuttle",

  // Misc fixes
  "Nissan/sunny": "Nissan/Sunny",
  "Nissan/Super safari": "Nissan/Patrol",
  "Nissan/4800 VTC": anonymousName,
  "Nissan/Ariya MPV": "Nissan/Ariya",
  "Ford/Focus RS": "Ford/Focus",
  "Ford/Puma Gen-E": "Ford/Puma",
  "Ford/Kuga 2019 (2024)": "Ford/Kuga",
  "Chevrolet/Equinox EV": "Chevrolet/Equinox",
  "Chevrolet/Blazer EV": "Chevrolet/Blazer",
  "Chevrolet/Silverado EV": "Chevrolet/Silverado 1500",
  "Chevrolet/Silverado HD": "Chevrolet/Silverado 2500HD",
  "GMC/HUMMER EV": "GMC/Hummer EV",
  "GMC/HUMMER EV SUV": "GMC/Hummer EV",
  "GMC/Sierra HD": "GMC/Sierra 2500HD",

]
