import Foundation

let anonymousName = "The stig"
// Typo corrections dictionary for vehicle series names
let typoCorrections: [String: String] = [
  "$$_posthog_breakdown_null_$$": anonymousName,
  "/": anonymousName,
  "/Civic": "Honda/Civic",
  "/Creta": "Hyundai/Creta",
  "/Giulia": "Alfa Romeo/Giulia",
  "/Teramount": "Volkswagen/Teramont",
  "2019/Mazda2": "Mazda/Mazda2",
  "Accent/": "Hyundai/Accent",
  "Alfa Romeo/Guilia": "Alfa Romeo/Giulia",
  "AUDIdi/Q3": "Audi/Q3",
  "Audu/S6 Avant e-tron": "Audi/S6 Avant e-tron",
  "Azera /MDE": "Hyundai/Azera",
  "B/B": anonymousName,
  "Bd/Hd": anonymousName,
  "Bdbb/Bzbxb": anonymousName,
  "BME/G20 330i": "BMW/G20 330i",
  "BMW/IX1": "BMW/iX1",
  "BMW/Serie 1 ": "BMW/Series 1",
  "Camry/24": "Toyota/Camry",
  "Camry/Camry": "Toyota/Camry",
  "Chanagan/Uni K": "Changan/UNI-K",
  "Changan /Uni-v": "Changan/UNI-V",
  "Changan /UNI-V": "Changan/UNI-V",
  "changan/uni-v": "Changan/UNI-V",
  "Changan/Uni-v": "Changan/UNI-V",
  "Changhan/Eado plse": "Changan/Eado Plus",
  "Cheery/Areezo8": "Chery/Arrizo 8",
  "Cherry /Teggo pro 7": "Chery/Tiggo 7 Pro",
  "Cherry/Arizo 6. Pro": "Chery/Arrizo 6 Pro",
  "CHERRY/Arrizo8": "Chery/Arrizo 8",
  "Cherry/Tiggo 8 pro": "Chery/Tiggo 8 Pro",
  "Chery /Tiggo 8 Pro": "Chery/Tiggo 8 Pro",
  "Chevorlat/Tahoe": "Chevrolet/Tahoe",
  "Chevorlet/Malibu": "Chevrolet/Malibu",
  "Chevrolet/Malibeu": "Chevrolet/Malibu",
  "Chevrolet/Taho": "Chevrolet/Tahoe",
  "Chevrolet3022/Blazer": "Chevrolet/Blazer",
  "Cxfhhhvv/Hhhc.": anonymousName,
  "Defender/2021": "Land Rover/Defender",
  "Defender/Defender": "Land Rover/Defender",
  "Eagle/Renulet megan": "Renault/Megane",
  "Elantra/Smart": "Hyundai/Elantra",
  "Ford Taurus/2023": "Ford/Taurus",
  "Ford/everest": "Ford/Everest",
  "Ford/EVEREST": "Ford/Everest",
  "Ford/Mavrick": "Ford/Maverick",
  "Ford/Ranger rapter": "Ford/Ranger Raptor",
  "Ford/ta": "Ford/Taurus",
  "Ford/Tauros": "Ford/Taurus",
  "Ford/Taurs": "Ford/Taurus",
  "Ford/Teratoury": "Ford/Territory",
  "Ford/Teritory": "Ford/Territory",
  "Ford/Terytory": "Ford/Territory",
  "Ford/Toto": "Ford/Taurus",
  "Ford/Touars": "Ford/Taurus",
  "Ford/Touros": "Ford/Taurus",
  "Ford/Tours": "Ford/Taurus",
  "Ford/Tourus": "Ford/Taurus",
  "Ford/Turas": "Ford/Taurus",
  "Ford/Tures": "Ford/Taurus",
  "Ford/Turua": "Ford/Taurus",
  "GMC/Sieera": "GMC/Sierra",
  "googl.com/": anonymousName,
  "hawndi/tucan": "Hyundai/Tucson",
  "Heundai/Azera": "Hyundai/Azera",
  "Hionday/Elantra": "Hyundai/Elantra",
  "Honda/Acurd": "Honda/Accord",
  "Honda/Oddyssey": "Honda/Odyssey",
  "Hondai/Accent": "Hyundai/Accent",
  "Hondi azera/": "Honda/Azera",
  "Hounday/T": "Hyundai/Tucson",
  "Hunda Accord /4dr": "Honda/Accord",
  "Hundai/Creta": "Hyundai/Creta",
  "Hundai/Krita": "Hyundai/Creta",
  "Hunday/Tucson": "Hyundai/Tucson",
  "Huyndai/Accent": "Hyundai/Accent",
  "Huyndai/Yuscon": "Hyundai/Tucson",
  "Hyandiy/Azera": "Hyundai/Azera",
  "Hyonday/Elentra": "Hyundai/Elantra",
  "Hyunai/Elantra": "Hyundai/Elantra",
  "Hyundai/Ionoiq 5": "Hyundai/IONIQ 5",
  "Hyundai6/Accent": "Hyundai/Accent",
  "Hyundi/Elantra": "Hyundai/Elantra",
  "Hyundi/Elentra": "Hyundai/Elantra",
  "hyundia /Sonata": "Hyundai/Sonata",
  "In korea/G80": "Genesis/G80",
  "Jeep/Grand Cherockee": "Jeep/Grand Cherokee",
  "Jetour /T2": "Jetour/T2",
  "JETOUR /T2": "Jetour/T2",
  "jetour/t2": "Jetour/T2",
  "K5/": "Kia/K5",
  "Kai/K5": "Kia/K5",
  "Kai/Optima": "Kia/Optima",
  "Kia/KIA5": "Kia/K5",
  "Kis/Ev9": "Kia/EV9",
  "Land Rover/Autobiograpgy": "Land Rover/Autobiography",
  "Luczs/Is259": "Lexus/IS 250",
  "Ma/Outback": "Subaru/Outback",
  "Maruti /Baleno": "Maruti Suzuki/Baleno",
  "Mazada/Mazada 6": "Mazda/Mazda6",
  "Mazda/MX-5 Miata RF": "Mazda/MX-5",
  "Mazda/MX-5 Miata": "Mazda/MX-5",
  "Mazda 6/": "Mazda/6",
  "Meganr/": "Renault/Megane",
  "Mercedec/G class": "Mercedes-Benz/G-Class",
  "Mercedes /": "Mercedes-Benz/",
  "Mercedes /Clk": "Mercedes-Benz/CLK",
  "Mercedes /G 63": "Mercedes-Benz/G 63 AMG",
  "Mercedes-Benzv/C 200": "Mercedes-Benz/C 200",
  "Mercedes/C200": "Mercedes-Benz/C 200",
  "Mercedes/C300": "Mercedes-Benz/C 300",
  "Mercedes/CLA250": "Mercedes-Benz/CLA 250",
  "Mercedes/Classe c": "Mercedes-Benz/C-Class",
  "Mercedes/E 300": "Mercedes-Benz/E 300",
  "Mercedes/E200": "Mercedes-Benz/E 200",
  "Mercedes/Ecitan": "Mercedes-Benz/Citan",
  "Mercedes/Gla 220": "Mercedes-Benz/GLA 220",
  "Mercedes/GLE 43 Coupe AMG": "Mercedes-Benz/GLE 43 AMG Coupe",
  "Mercedes/Gle 53 coupe": "Mercedes-Benz/GLE 53 AMG Coupe",
  "Mercedes/Sprinter": "Mercedes-Benz/Sprinter",
  "Mercedez-Benz/Glc": "Mercedes-Benz/GLC",
  "MG-ZS/": "MG/ZS",
  "Nisaan /Patrol": "Nissan/Patrol",
  "Nisaan/patrol": "Nissan/Patrol",
  "Nisaan/Platinum": "Nissan/Patrol Platinum",
  "Nisan NISMO /2024": "Nissan/370Z NISMO",
  "Nissan Altama/S": "Nissan/Altima",
  "Nissan/ALITMIMA": "Nissan/Altima",
  "Nissan/Altama": "Nissan/Altima",
  "Nissan/Qashqaj": "Nissan/Qashqai",
  "Nissan/The tima": "Nissan/Altima",
  "Nussan/Patrol": "Nissan/Patrol",
  "Opel /Opel mokka": "Opel/Mokka",
  "OPEL/Astra Sports Tourwr": "OPEL/Astra Sports Tourer",
  "OPEL/Granland": "OPEL/Grandland",
  "OPEL/Insigna": "OPEL/Insignia",
  "P/E": anonymousName,
  "Pe/3008": "Peugeot/3008",
  "peugeot iran khodro/207": "Peugeot/207",
  "Porsxhe/Taycan": "Porsche/Taycan",
  "rabdan/one": anonymousName,
  "Range Rover /Velar": "Land Rover/Range Rover Velar",
  "Renoult/Clio 4": "Renault/Clio IV",
  "Rox 01 /Rox 01": anonymousName,
  "Sangyoung/Rexston": "SsangYong/Rexton",
  "Skods/Octavia": "Skoda/Octavia",
  "SssngYong/": "SsangYong/",
  "suzki/": "Suzuki/",
  "TAURUS/2025": "Ford/Taurus",
  "Taurus/Titanim": "Ford/Taurus",
  "Touots /corolla": "Toyota/Corolla",
  "Toyoa/Land crusier": "Toyota/Land Cruiser",
  "Toyota land cruiser/LC300": "Toyota/Land Cruiser LC300",
  "Toyota/corola": "Toyota/Corolla",
  "Toyota/Corola": "Toyota/Corolla",
  "Toyota/Hillux": "Toyota/Hilux",
  "Toyota/Land crusier": "Toyota/Land Cruiser",
  "Toyta/Crolla": "Toyota/Corolla",
  "Unknown": anonymousName,
  "Unknown/Unknown": anonymousName,
  "Vauxhall /Insignia": "Vauxhall/Insignia",
  "Vauxhaull/Astra": "Vauxhall/Astra",
  "Vlvo/V70": "Volvo/V70",
  "volkeswagen/tiguan": "Volkswagen/Tiguan",
  "Volkswageb/Poli": "Volkswagen/Polo",
  "Volkswagee/Virtus": "Volkswagen/Virtus",
  "Volkswagen/Goal": "Volkswagen/Golf",
  "Volkswagen/Golff": "Volkswagen/Golf",
  "Volkswagen/Pasat": "Volkswagen/Passat",
  "Volkswagen/T roc cabriolet": "Volkswagen/T-Roc Cabriolet",
  "Volkswagen/Tcross 2021": "Volkswagen/T-Cross",
  "Volkswagen/Twareg": "Volkswagen/Touareg",
  "Volkwagen/Virtus": "Volkswagen/Virtus",
  "VW/Id.6": "Volkswagen/ID.6",
  "VW/Id3": "Volkswagen/ID.3",
  "Vw/Id4": "Volkswagen/ID.4",
  "VW/ID4": "Volkswagen/ID.4",
  "VW/ID6": "Volkswagen/ID.6",
  "Vw/Idbuzz": "Volkswagen/ID.Buzz",
  "WVGZZZ5NZMW541659/": anonymousName,
  "Xbb/Jxbxj": anonymousName,
  // Additional typo corrections from leaderboard review
  "AGM/GMX 450": anonymousName,
  "Bmw/740li": "BMW/740Li",
  "Chary/Tigoo8 pro": "Chery/Tiggo 8 Pro",
  "Chevy/Sonic": "Chevrolet/Sonic",
  "Chevorlet/Grove": "Chevrolet/Groove",
  "Ford/expdition": "Ford/Expedition",
  "Fordtaurus/Taurus": "Ford/Taurus",
  "Gacambao/athlete": anonymousName,
  "Greatwallmotor/HAVAL JOLION": "GWM/Haval Jolion",
  "Hindai/Elntra": "Hyundai/Elantra",
  "Honda/Accourd": "Honda/Accord",
  "Honda/Accrod": "Honda/Accord",
  "Honda/Acord": "Honda/Accord",
  "Honda/Cvic": "Honda/Civic",
  "Honda/Pliot": "Honda/Pilot",
  "Hondai/Taycan": "Porsche/Taycan",
  "Hundai/2025": anonymousName,
  "Hynday/Azera": "Hyundai/Azera",
  "Hyndai/Sonata": "Hyundai/Sonata",
  "Hyundia/Ioniq 5": "Hyundai/IONIQ 5",
  "Hyundia/Sonata": "Hyundai/Sonata",
  "Hyundai/Azira": "Hyundai/Azera",
  "Hyundai/Elentra": "Hyundai/Elantra",
  "Hyundai/Elantr": "Hyundai/Elantra",
  "Hyundai/ELNTRA": "Hyundai/Elantra",
  "Hyundai/GRANDUAR": "Hyundai/Grandeur",
  "Hyundai/Somata": "Hyundai/Sonata",
  "Land Rover/Devender": "Land Rover/Defender",
  "Lexus/Lexus": anonymousName,
  "Lexus/Rx450+": "Lexus/RX 450h",
  "Linclon/Neutilus": "Lincoln/Nautilus",
  "Nissan/Nissan Patrol": "Nissan/Patrol",
  "Nissanpatrol/Patrol": "Nissan/Patrol",
  "Renault/Kadjarr": "Renault/Kadjar",
  "Renoult/Clio 4": "Renault/Clio IV",
  "Sonata/2025": "Hyundai/Sonata",
  "Toyota/Camrey": "Toyota/Camry",
  "Toyota/Cammry": "Toyota/Camry",
  "Toyota/HILLIX": "Toyota/Hilux",
  "Toyota/Land Crusier LC300": "Toyota/Land Cruiser LC300",
  "Toyota/Land cruser": "Toyota/Land Cruiser",
  "Toyota/Land cruiser VXR": "Toyota/Land Cruiser",
  "Toyote/Land cruiser": "Toyota/Land Cruiser",
  "Toyotaw/Crown": "Toyota/Crown",
  "Volkswag/Fox": "Volkswagen/Fox",
  "Volvov/XC60": "Volvo/XC60",
  "Yoyota/Corolla": "Toyota/Corolla",
]
