name: Daily PostHog Export

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  export-data:
    runs-on: macos-15
    
    env:
      POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
      POSTHOG_PROJECT_ID: ${{ secrets.POSTHOG_PROJECT_ID }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Build and run analytics package
        run: |
          swift run analytics
        env:
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
          POSTHOG_PROJECT_ID: ${{ secrets.POSTHOG_PROJECT_ID }}
          
      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
      - name: Commit and push changes
        run: |
          git add Sources/gensite/
          git commit -m "Update PostHog export data [skip ci]" || echo "No changes to commit"
          git push origin main

